#!/bin/bash

set -e
shopt -s nullglob

SCRIPT=$(basename $0)
PATHS=() # Bash array

PAGEROTATE=""

usage()
{
    cat <<EOF
Usage: $SCRIPT [--help] images ..."

required arguments:
  images        SVG files to be converted to Gcode

optional arguments:
  --pagerotate  rotate SVG 90 degrees before converting to Gcode
  -h, --help    show this message and exit

examples:
  $SCRIPT foo.svg
EOF
}

store_image_path() {
    if [ -e "$1" ]; then
            PATHS+=("$1")
    else
        echo "Unknown argument: $1"
        usage
        exit 1
    fi
}

while [ "$1" != "" ]; do
    case $1 in
        --pagerotate )          PAGEROTATE="pagerotate"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     store_image_path "$1"
                                ;;
    esac
    shift
done

for img in "${PATHS[@]}"; do
    FILENAME_EXTENSIONLESS="${img%.*}"
    vpype --config "vpype.toml" \
    read "${FILENAME_EXTENSIONLESS}.svg" \
    occult linesort $PAGEROTATE \
    gwrite --profile "my_own_plotter" \
    "${FILENAME_EXTENSIONLESS}.gcode"
done
