[gwrite.my_own_plotter]
unit = "mm"
document_start = "G17;G21;G28;G90;G1 F4000;M3 S05;G4 P0.3\n"
document_end = "M3 S05;G4 P0.3;G1 X.000 Y.000\n"
line_start = "M3 S120;G4 P0.3\n"
line_end = "M3 S05;G4 P0.3\n"
