[gwrite.my_own_plotter]
unit = "mm"

document_start = """G17
G21
G28
G90
G1 F4000
M3 S05
G4 P0.3
"""

document_end = """M3 S05
G4 P0.3
G1 X.000 Y.000"""

line_start = """M3 S120
G4 P0.3"""

line_end = """M3 S05
G4 P0.3
"""

segment_first = """G00 X{x:.4f} Y{y:.4f}
"""

segment = """G01 X{x:.4f} Y{y:.4f}
"""
